# Generated by Django 4.1.7 on 2024-08-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="User_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=50)),
                (
                    "affiliation",
                    models.CharField(db_column="Affiliation", max_length=50),
                ),
                ("position", models.CharField(db_column="Position", max_length=50)),
                ("dob", models.DateField(db_column="Dob")),
                ("phone", models.CharField(db_column="Phone", max_length=30)),
                (
                    "email",
                    models.EmailField(db_column="Email", max_length=255, unique=True),
                ),
                (
                    "username",
                    models.CharField(db_column="Username", max_length=40, unique=True),
                ),
                ("password", models.CharField(db_column="Password", max_length=255)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
