# Generated by Django 4.1.7 on 2024-08-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("management", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "user_id",
                    models.IntegerField(
                        db_column="User_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=10)),
                (
                    "affiliation",
                    models.CharField(db_column="Affiliation", max_length=10),
                ),
                ("position", models.CharField(db_column="Position", max_length=10)),
                ("dob", models.CharField(db_column="Dob", max_length=10)),
                ("phone", models.CharField(db_column="Phone", max_length=30)),
                ("email", models.CharField(db_column="Email", max_length=40)),
                ("username", models.CharField(db_column="Username", max_length=40)),
                ("password", models.CharField(db_column="Password", max_length=40)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
